"use strict";
const fs=require("fs");
const assert=require("assert");
const pkg=JSON.parse(fs.readFileSync("package.json","utf8"));
const bootstrap=fs.readFileSync("line-app-bootstrap.js","utf8");
const safety=fs.readFileSync("line-image-safety.js","utf8");
const start=String(pkg.scripts?.start||"");
assert(start.includes("-r ./line-app-bootstrap.js"),"正式啟動沒有預載LINE媒體路由bootstrap");
assert(bootstrap.includes('safety.installImageRoutes(app)'),"bootstrap沒有把正式媒體路由掛到實際Express app");
assert(bootstrap.includes('formal-dm-routes-mounted-on-runtime-app'),"bootstrap缺少正式媒體路由能力標記");
assert(safety.includes('app.get("/assets/formal-dm/:id.jpg"'),"正式媒體安全層缺少DM／試喝JPEG路由");
assert(safety.includes('resize({ width: 1024, height: 1024, fit: "inside"'),"正式DM轉LINE JPEG必須等比例縮放、不可裁切");
assert(safety.includes('products-v3-remains-identity-authority'),"正式DM顯示不得取代products-v3產品識別權威");
console.log("PASS：LINE正式啟動會掛載DM／試喝JPEG路由，並保留等比例與products-v3產品權威；守門驗能力、不綁舊版號。");
