"use strict";
const assert = require("assert");
const fs = require("fs");
const { validateData, sanitizeUserText, cleanupExpiredStates, VERSION } = require("./server");
const source = fs.readFileSync("server.js", "utf8");
assert.strictEqual(VERSION, "v300.7");
assert.ok(source.includes('const CRM_URL = process.env.CRM_URL || "https://script.google.com/macros/s/AKfycbwAFBxeROd2ZYGJ_h0O7_H2MMxptOMoj3EXIErZpbKuTYFOzOVwQkrk8X1MoxapkHVGSA/exec";'));
assert.ok(!/channelAccessToken:\s*process\.env\.CHANNEL_ACCESS_TOKEN\s*\|\|\s*["\'][A-Za-z0-9+/=]{40,}/.test(source));
assert.ok(!/channelSecret:\s*process\.env\.CHANNEL_SECRET\s*\|\|\s*["\'][a-f0-9]{32}/i.test(source));
assert.strictEqual(sanitizeUserText("  王\u0000 小明  ", 40), "王 小明");
assert.strictEqual(sanitizeUserText("abcdef", 3), "abc");
assert.throws(() => validateData({ products: [] }), /products/);
cleanupExpiredStates(Date.now());
console.log("PASS security and UX v300.7");
