"use strict";

const assert = require("assert");
const {
  CAMPAIGN_ID,
  MASCOT_CAMPAIGN_ID,
  TOPICS,
  imageUrl,
  instagramCaption,
  facebookCaption,
} = require("./social-product-content-rebuild");
const {
  currentHealth,
  removeAutoGeneratedSchedule,
} = require("./social-product-content-bootstrap");

assert.strictEqual(TOPICS.length, 20, "產品與品牌素材必須剛好20篇");
assert.strictEqual(new Set(TOPICS.map((topic) => topic.slug)).size, 20, "slug不可重複");
assert.strictEqual(new Set(TOPICS.map((topic) => topic.number)).size, 20, "編號不可重複");

for (const topic of TOPICS) {
  assert.ok(imageUrl(topic).startsWith("https://ts15825868.github.io/xianjiawei/"), `${topic.slug} 圖片必須來自正式官網`);
  assert.ok(/images\/(dm-final|products-v3)\//.test(topic.image), `${topic.slug} 必須使用正式產品圖或DM`);
  assert.ok(instagramCaption(topic).includes("@762jybnm"), `${topic.slug} IG文案缺少LINE`);
  assert.ok(facebookCaption(topic).includes("@762jybnm"), `${topic.slug} FB文案缺少LINE`);
  const combined = `${topic.title}\n${topic.lead}\n${topic.bullets.join("\n")}`;
  for (const prohibited of ["治療", "療效", "改善疾病", "治癒", "預防疾病"]) {
    assert.ok(!combined.includes(prohibited), `${topic.slug} 出現不允許的醫療宣稱：${prohibited}`);
  }
}

const productPublished = {
  id: "product-published-keep",
  campaignId: CAMPAIGN_ID,
  title: "已發布產品貼文",
  status: "published",
  scheduledAt: "2026-07-15T12:00:00.000Z",
};
const productDraft = {
  id: "product-draft-remove",
  campaignId: CAMPAIGN_ID,
  title: "舊自動產品草稿",
  status: "draft",
};
const productApproved = {
  id: "product-approved-remove",
  campaignId: CAMPAIGN_ID,
  title: "舊自動產品排程",
  status: "approved",
};
const mascotDraft = {
  id: "mascot-draft-keep",
  campaignId: MASCOT_CAMPAIGN_ID,
  title: "正式小老闆待審",
  status: "draft",
};
const otherPublished = {
  id: "other-published-keep",
  campaignId: "manual-campaign",
  title: "其他已發布貼文",
  status: "published",
};

let store = {
  posts: [productPublished, productDraft, productApproved, mascotDraft, otherPublished],
};
const result = removeAutoGeneratedSchedule(
  () => store,
  (next) => { store = next; }
);

assert.strictEqual(result.autoGeneratedScheduleEnabled, false, "舊自動產品排程必須停用");
assert.strictEqual(result.removedAutoGenerated, 2, "必須清除所有尚未發布的舊自動產品貼文");
assert.strictEqual(result.preservedPublished, 1, "必須保留產品活動已發布紀錄");
assert.ok(store.posts.some((post) => post.id === productPublished.id), "產品已發布紀錄不得刪除");
assert.ok(store.posts.some((post) => post.id === mascotDraft.id), "正式小老闆待審內容不得刪除");
assert.ok(store.posts.some((post) => post.id === otherPublished.id), "其他活動已發布紀錄不得刪除");
assert.ok(!store.posts.some((post) => post.id === productDraft.id), "舊自動產品草稿不得保留");
assert.ok(!store.posts.some((post) => post.id === productApproved.id), "舊自動產品排程不得保留");

const health = currentHealth(() => store);
assert.strictEqual(health.ok, true, "清理後健康檢查必須正常");
assert.strictEqual(health.state, "disabled", "舊自動產品排程狀態必須為停用");
assert.strictEqual(health.activeTotal, 0, "不得殘留任何舊自動產品排程");

console.log("PASS 20篇正式產品文案安全檢查；舊自動產品排程保持停用，保留已發布紀錄與正式小老闆待審內容。");
