"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),zlib=require("zlib");
const root=path.resolve(__dirname,"..");
const read=f=>fs.readFileSync(path.join(root,f),"utf8");
const exists=f=>fs.existsSync(path.join(root,f));
const json=f=>JSON.parse(read(f));
const decode=f=>zlib.gunzipSync(Buffer.from(read(f).replace(/\s+/g,""),"base64")).toString("utf8");
const required=["server.js","internal-entry.js","internal-app-client-fix.js","internal-social-site.js","internal-social-site/index.html.gz.b64","internal-social-site/site.css.gz.b64","internal-social-site/site.js.gz.b64","social-server.js","social-final-posts.js","social-final-approved-batch.js","social-review-only-mode.js","social-weekly-schedule-override.js","social-schedule-policy.js","social-schedule-repair-20260722.js","social-static-asset-bridge.js","social-publish-guard.js","product-sales-master.js","product-quote-only-guard.js","brand-content.json","brand-content-runtime.js","line-sales-master.json","MASCOT_CHARACTER_SPEC.md","supabase-state-bridge.js","persistence-auto-save.js"];
for(const f of required)assert(exists(f),`缺少正式檔案：${f}`);
const data=json("data.json"),pkg=json("package.json"),lock=json("package-lock.json"),sales=json("line-sales-master.json"),brand=json("brand-content.json");
const weekly=require("../social-weekly-schedule-override"),reviewGate=require("../social-review-only-mode"),scheduleRepair=require("../social-schedule-repair-20260722"),schedulePolicy=require("../social-schedule-policy"),finalPosts=require("../social-final-posts"),approvedBatch=require("../social-final-approved-batch"),quoteGuard=require("../product-quote-only-guard");
assert.equal(data.lineId,"@762jybnm");assert.equal(data.catalogVersion,"408.9");assert.equal(data.products.length,6);assert.equal(pkg.version,"6.1.1");assert.equal(lock.version,pkg.version);assert.equal(lock.packages?.[""]?.version,pkg.version);
assert.equal(sales.version,"2026-07-28-v7");
const expected={"guilu-gao":{price:1500,originalPrice:1800},"guilu-drink-30":{price:50,offer:"買10送2",name:"龜鹿飲30cc玻璃罐",specification:"30cc／罐（小玻璃罐）",unit:"罐"},"guilu-drink-180":{price:200,offer:"買10送2"},"guilu-tangkuai":{price:1600,name:"龜鹿湯塊75g",specification:"75g／盒｜8塊裝｜每塊約9.375g",unit:"盒"},"luerong-fen":{price:2000},"guilu-jiao":{price:9600,originalPrice:12000,quoteOnly:false,name:"龜鹿膠",specification:"600g／盒（1斤）｜32塊裝｜每塊約18.75g",unit:"盒"}};
for(const[id,r]of Object.entries(expected)){const p=sales.products?.[id];assert(p,`缺少正式產品：${id}`);assert.equal(Number(p.price),r.price,`${id} 售價錯誤`);if(r.originalPrice!==undefined)assert.equal(Number(p.originalPrice),r.originalPrice,`${id} 原價錯誤`);if(r.offer)assert(p.offers?.includes(r.offer),`${id} 優惠錯誤`);if(r.quoteOnly!==undefined)assert.equal(p.quoteOnly,r.quoteOnly,`${id} 下單模式錯誤`);if(r.name!==undefined)assert.equal(p.name,r.name,`${id} 名稱錯誤`);if(r.specification!==undefined){assert.equal(p.specification,r.specification,`${id} specification 錯誤`);assert.equal(p.size,r.specification,`${id} size 錯誤`);assert.equal(p.spec,r.specification,`${id} spec 錯誤`);}if(r.unit!==undefined)assert.equal(p.unit,r.unit,`${id} 單位錯誤`);}
assert.equal(sales.comboOffers?.length,3);assert.equal(sales.combos?.length,3);assert.deepEqual(sales.imagePolicy?.partners,["小鹿娃娃","小烏龜娃娃"]);assert.equal(sales.imagePolicy?.realProductImagesOnly,true);assert.equal(sales.imagePolicy?.noProductRedraw,true);assert.equal(sales.imagePolicy?.approvalRequiredBeforePublish,true);
for(const label of["品牌故事","品牌由來","選料理念","品質把關","傳統工法","品牌承諾"]){assert.equal(typeof brand.quickReplies?.[label],"string",`品牌內容缺少：${label}`);assert(brand.quickReplies[label].trim().length>=20,`品牌內容過短：${label}`);}
assert.equal(brand.brand,"仙加味");assert.equal(brand.tagline,"補養，是一種節奏。");assert(Array.isArray(brand.menu)&&brand.menu.length>=5,"品牌導覽不足");assert(read("brand-content-runtime.js").includes("content.quickReplies"),"LINE 尚未載入目前品牌內容格式");
const start=String(pkg.scripts?.start||"");for(const f of["product-sales-master.js","brand-content-runtime.js","product-quote-only-guard.js","social-weekly-schedule-override.js","social-review-only-mode.js","social-static-asset-bridge.js"])assert(start.includes(f),`正式啟動缺少：${f}`);assert(start.indexOf("product-sales-master.js")<start.indexOf("product-quote-only-guard.js"),"售價主檔載入順序錯誤");assert(!start.includes("social-incomplete-auto-retry.js"),"不可載入失敗平台自動補發模組");
assert.equal(weekly.VERSION,"2026-07-25-weekly-once-v1");assert.equal(reviewGate.VERSION,"2026-07-26-review-gate-v5");assert.equal(scheduleRepair.VERSION,"2026-07-25-v6");assert.equal(approvedBatch.VERSION,"6.1.0");assert.equal(approvedBatch.WEATHER_RATE_LIMIT_BACKOFF_MS,7200000);
const posts=finalPosts.POSTS;assert.equal(posts.length,10);for(const f of["id","title","instagramCaption","facebookCaption","imageName"])assert.equal(new Set(posts.map(p=>p[f])).size,10,`貼文 ${f} 不可重複`);assert(posts.every(p=>p.qBossMascotLocked&&p.deerPartnerPresent&&p.turtlePartnerPresent),"小老闆固定夥伴規格不完整");const fixed=posts.filter(p=>!p.conditionalWeather),weather=posts.filter(p=>p.conditionalWeather);assert.equal(fixed.length,7);assert.equal(weather.length,3);assert(weather.every(p=>!p.scheduledAt&&p.automationStandby===true),"天氣貼文不可預排");const weeks=new Map();for(const p of fixed){assert(schedulePolicy.validScheduledAt(p.scheduledAt,p),`${p.title} 不是週三20:00`);const k=schedulePolicy.weekKey(p.scheduledAt);weeks.set(k,(weeks.get(k)||0)+1);}assert([...weeks.values()].every(n=>n===1),"同一週不可超過一篇固定貼文");
assert.equal(quoteGuard.VERSION,"2026-07-25-quote-only-v2");assert(quoteGuard.transformServer(read("server.js")).includes("if (product.quoteOnly) return false"));const html=decode("internal-social-site/index.html.gz.b64"),css=decode("internal-social-site/site.css.gz.b64"),js=decode("internal-social-site/site.js.gz.b64");assert(html.includes("社群管理中心")&&html.includes('id="imageFile"'));assert(css.includes(".post-card"));assert(js.includes("/internal/api/v2/social/upload"));assert(!js.includes("MutationObserver"));assert(read("social-static-asset-bridge.js").includes("NotoSansTC-VF.ttf"));assert(read("social-static-asset-bridge.js").includes("preventsGibberish: true"));assert(read("social-publish-guard.js").includes("withPostLock"));assert(read("social-publish-guard.js").includes("recordPublication"));
console.log("仙加味正式檢查通過：LINE OA v6.1.1、六項售價與優惠、龜鹿膠600g完整規格、共用品牌內容、十篇待審、週三20:00排程、天氣條件加發、真實產品圖與固定角色夥伴。");